---
deployment:
  tasks:
    - export DEPLOYPATH=/home3/metap8ok/myomr.in/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/rsync -av --delete --exclude ".git" --exclude "uploads" --exclude "sessions" --exclude ".env" --exclude "logs" --exclude "log" --exclude "error_log" ./ $DEPLOYPATH
