<?php
/**
 * MyOMR — Master Sitemap Index Generator
 * Served at https://myomr.in/sitemap.xml via .htaccess rewrite.
 *
 * This file is a SITEMAP INDEX: it lists ~12 child sitemap URLs, not 200+ page URLs.
 * The 200+ pages live inside those child sitemaps (sitemap-pages, omr-listings, jobs, events, etc.).
 * Open each <loc> URL in a browser to see the actual page URLs per section.
 *
 * To add a new module: append a $sitemaps[] entry below.
 */

header('Content-Type: application/xml; charset=UTF-8');
header('X-Robots-Tag: noindex');

$base    = 'https://myomr.in';
$today   = date('Y-m-d');

$sitemaps = [
    // Static pages (core, info, discover-myomr) — generated by generate-sitemap-pages.php
    ['loc' => $base . '/sitemap-pages.xml',                                    'lastmod' => $today],

    // Local News articles (dynamic – generated from DB)
    ['loc' => $base . '/local-news/sitemap.xml',                               'lastmod' => $today],

    // OMR Listings: schools, hospitals, banks, parks, industries, ATMs, etc.
    ['loc' => $base . '/omr-listings/sitemap.xml',                             'lastmod' => $today],

    // IT Parks detail pages
    ['loc' => $base . '/it-parks/sitemap.xml',                                 'lastmod' => $today],

    // Local Events
    ['loc' => $base . '/omr-local-events/sitemap.xml',                        'lastmod' => $today],

    // Job Portal
    ['loc' => $base . '/omr-local-job-listings/sitemap.xml',                  'lastmod' => $today],

    // Hostels & PGs
    ['loc' => $base . '/omr-hostels-pgs/sitemap.xml',                         'lastmod' => $today],

    // Coworking Spaces
    ['loc' => $base . '/omr-coworking-spaces/sitemap.xml',                    'lastmod' => $today],

    // Buy & Sell
    ['loc' => $base . '/omr-buy-sell/sitemap.xml',                            'lastmod' => $today],
    ['loc' => $base . '/omr-classified-ads/sitemap.xml',                      'lastmod' => $today],

    // Pentahive
    ['loc' => $base . '/pentahive/sitemap.xml',                               'lastmod' => $today],

    // Elections 2026 subsite
    ['loc' => $base . '/elections-2026/sitemap.xml',                           'lastmod' => $today],
];

echo '<?xml version="1.0" encoding="UTF-8"?>' . "\n";
echo '<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' . "\n";

$xmlFlags = defined('ENT_XML1') ? (ENT_XML1 | ENT_QUOTES) : ENT_QUOTES;
foreach ($sitemaps as $s) {
    echo "  <sitemap>\n";
    echo '    <loc>' . htmlspecialchars($s['loc'] ?? '', $xmlFlags, 'UTF-8') . "</loc>\n";
    echo '    <lastmod>' . ($s['lastmod'] ?? $today) . "</lastmod>\n";
    echo "  </sitemap>\n";
}

echo '</sitemapindex>' . "\n";
