<?php
/**
 * Unified navigation registry for MyOMR admin.
 * Structure powers the sidebar, dashboard index, and future menu builders.
 */

return [
    [
        'key' => 'dashboard_content',
        'label' => 'Dashboard & Content',
        'icon' => 'fa-gauge-high',
        'modules' => [
            [
                'key' => 'dashboard',
                'name' => 'Command Center',
                'description' => 'Live stats, recent activity, and quick links across every MyOMR module.',
                'path' => '/superadmin/index.php',
                'icon' => 'fa-chart-pie',
                'tags' => ['dashboard', 'overview', 'analytics'],
                'actions' => [
                    ['label' => 'GA4 overview (API)', 'path' => '/superadmin/ga4-overview.php'],
                    ['label' => 'News Publisher', 'path' => '/superadmin/news-publisher.php'],
                ],
            ],
            [
                'key' => 'articles',
                'name' => 'News Articles',
                'description' => 'Articles table: homepage news cards + /local-news/ detail pages. Primary news system.',
                'path' => '/superadmin/articles/index.php',
                'icon' => 'fa-newspaper',
                'tags' => ['news', 'content', 'articles', 'homepage'],
                'actions' => [
                    ['label' => 'Token-Free Publisher', 'path' => '/superadmin/news-publisher.php'],
                    ['label' => 'Add Article', 'path' => '/superadmin/articles/add.php'],
                ],
            ],
            [
                'key' => 'events',
                'name' => 'Events Control (legacy)',
                'description' => 'Legacy events table CMS — separate from Community Events submissions.',
                'path' => '/superadmin/events/events-list.php',
                'icon' => 'fa-calendar-days',
                'tags' => ['events', 'calendar'],
                'actions' => [
                    ['label' => 'Add Event', 'path' => '/superadmin/events/events-add.php'],
                    ['label' => 'Events Analytics', 'path' => '/superadmin/events-analytics.php'],
                ],
            ],
            [
                'key' => 'jobs',
                'name' => 'Jobs Portal',
                'description' => 'Manage job listings, approvals, and featured roles.',
                'path' => '/superadmin/jobs/index.php',
                'icon' => 'fa-briefcase',
                'tags' => ['jobs', 'careers', 'employment'],
                'actions' => [
                    ['label' => 'Manage Jobs', 'path' => '/superadmin/jobs/manage-jobs-omr.php'],
                    ['label' => 'Featured jobs', 'path' => '/superadmin/jobs/manage-jobs-omr.php?featured=1'],
                    ['label' => 'Verify Employers', 'path' => '/superadmin/jobs/verify-employers-omr.php'],
                    ['label' => 'All Applications', 'path' => '/superadmin/jobs/view-all-applications-omr.php'],
                    ['label' => 'Package subscribers', 'path' => '/superadmin/jobs/package-subscribers-omr.php'],
                    ['label' => 'Job seeker profiles', 'path' => '/superadmin/manage-job-seeker-profiles-omr.php'],
                ],
            ],
            [
                'key' => 'community_events',
                'name' => 'Community Events',
                'description' => 'Moderate event submissions and manage published community events.',
                'path' => '/superadmin/community-events/index.php',
                'icon' => 'fa-calendar-check',
                'tags' => ['events', 'community', 'submissions'],
                'actions' => [
                    ['label' => 'Manage Submissions', 'path' => '/superadmin/community-events/manage-events-omr.php'],
                    ['label' => 'View Listings', 'path' => '/superadmin/community-events/view-listings.php'],
                    ['label' => 'Calendar export', 'path' => '/superadmin/community-events/calendar-export.php'],
                ],
            ],
            [
                'key' => 'hostels_pgs',
                'name' => 'Hostels & PGs',
                'description' => 'Oversee hostel, PG, and co-living listings along OMR.',
                'path' => '/superadmin/hostels/index.php',
                'icon' => 'fa-building-user',
                'tags' => ['hostel', 'pg', 'property'],
                'actions' => [
                    ['label' => 'Manage Properties', 'path' => '/superadmin/hostels/manage-properties.php'],
                    ['label' => 'Manage Owners', 'path' => '/superadmin/hostels/manage-owners.php'],
                    ['label' => 'View Inquiries', 'path' => '/superadmin/hostels/view-all-inquiries.php'],
                    ['label' => 'Featured management', 'path' => '/superadmin/hostels/featured-management.php'],
                ],
            ],
            [
                'key' => 'rent_lease',
                'name' => 'Rent & Lease',
                'description' => 'Manage house, apartment, and land listings for rent/lease in OMR.',
                'path' => '/superadmin/rent-lease/index.php',
                'icon' => 'fa-house',
                'tags' => ['rent', 'lease', 'property'],
                'actions' => [
                    ['label' => 'Manage Properties', 'path' => '/superadmin/rent-lease/manage-properties-omr.php'],
                    ['label' => 'Pending queue', 'path' => '/superadmin/rent-lease/manage-properties-omr.php?status=pending'],
                    ['label' => 'Upload Photos', 'path' => '/superadmin/rent-lease/upload-property-images-omr.php'],
                ],
            ],
            [
                'key' => 'buy_sell',
                'name' => 'Buy & Sell',
                'description' => 'Manage buy/sell classifieds listings in OMR.',
                'path' => '/superadmin/buy-sell/index.php',
                'icon' => 'fa-shopping-bag',
                'tags' => ['buy', 'sell', 'classifieds'],
                'actions' => [
                    ['label' => 'Manage Listings', 'path' => '/superadmin/buy-sell/manage-listings-omr.php'],
                    ['label' => 'Manage Categories', 'path' => '/superadmin/buy-sell/manage-categories-omr.php'],
                    ['label' => 'Reports', 'path' => '/superadmin/buy-sell/view-reports-omr.php'],
                ],
            ],
            [
                'key' => 'classified_ads',
                'name' => 'OMR Classified Ads',
                'description' => 'Approve services, wanted, and community notice listings (10-day expiry).',
                'path' => '/superadmin/classified-ads/index.php',
                'icon' => 'fa-newspaper',
                'tags' => ['classifieds', 'community', 'moderation'],
                'actions' => [
                    ['label' => 'Manage Listings', 'path' => '/superadmin/classified-ads/manage-listings-omr.php'],
                    ['label' => 'Reports', 'path' => '/superadmin/classified-ads/view-reports-omr.php'],
                ],
            ],
            [
                'key' => 'coworking',
                'name' => 'Coworking Spaces',
                'description' => 'Manage coworking space listings, approvals, and featured slots.',
                'path' => '/superadmin/coworking/index.php',
                'icon' => 'fa-building',
                'tags' => ['coworking', 'property', 'workspaces'],
                'actions' => [
                    ['label' => 'Manage Spaces', 'path' => '/superadmin/coworking/manage-spaces.php'],
                    ['label' => 'Manage Owners', 'path' => '/superadmin/coworking/manage-owners.php'],
                    ['label' => 'View Inquiries', 'path' => '/superadmin/coworking/view-all-inquiries.php'],
                    ['label' => 'Featured management', 'path' => '/superadmin/coworking/featured-management.php'],
                ],
            ],
            [
                'key' => 'restaurants',
                'name' => 'Restaurants & Cafés',
                'description' => 'Curate restaurant listings, menus, and availability.',
                'path' => '/superadmin/restaurants-list.php',
                'icon' => 'fa-utensils',
                'tags' => ['restaurants', 'food', 'dining'],
                'actions' => [
                    ['label' => 'Add Restaurant', 'path' => '/superadmin/restaurants-add.php'],
                ],
            ],
        ],
    ],
    [
        'key' => 'directories',
        'label' => 'Local Directories',
        'icon' => 'fa-city',
        'modules' => [
            [
                'key' => 'banks',
                'name' => 'Banks Directory',
                'description' => 'List and edit bank profiles. Use Manage Banks for delete operations.',
                'path' => '/superadmin/banks-list.php',
                'icon' => 'fa-landmark',
                'tags' => ['banks', 'finance', 'directories'],
                'actions' => [
                    ['label' => 'Manage Banks', 'path' => '/superadmin/manage-banks.php'],
                ],
            ],
            [
                'key' => 'schools',
                'name' => 'Schools & Colleges',
                'description' => 'Oversee educational listings, contact info, and facilities.',
                'path' => '/superadmin/schools-list.php',
                'icon' => 'fa-graduation-cap',
                'tags' => ['schools', 'education', 'directories'],
                'actions' => [
                    ['label' => 'Manage Schools', 'path' => '/superadmin/manage-schools.php'],
                ],
            ],
            [
                'key' => 'hospitals',
                'name' => 'Hospitals & Clinics',
                'description' => 'Maintain healthcare providers and emergency contacts.',
                'path' => '/superadmin/hospitals-list.php',
                'icon' => 'fa-house-medical',
                'tags' => ['hospitals', 'health', 'directories'],
                'actions' => [
                    ['label' => 'Manage Hospitals', 'path' => '/superadmin/manage-hospitals.php'],
                ],
            ],
            [
                'key' => 'parks',
                'name' => 'Parks & Recreation',
                'description' => 'Update parks, recreation spaces, and amenities.',
                'path' => '/superadmin/parks-list.php',
                'icon' => 'fa-tree',
                'tags' => ['parks', 'outdoor', 'directories'],
                'actions' => [
                    ['label' => 'Manage Parks', 'path' => '/superadmin/manage-parks.php'],
                    ['label' => 'Edit park', 'path' => '/superadmin/parks-list.php'],
                ],
            ],
            [
                'key' => 'industries',
                'name' => 'Industrial Directory',
                'description' => 'Manage industrial hubs and company listings.',
                'path' => '/superadmin/industries-list.php',
                'icon' => 'fa-industry-windows',
                'tags' => ['industries', 'business', 'directories'],
                'actions' => [
                    ['label' => 'Manage Industries', 'path' => '/superadmin/manage-industries.php'],
                ],
            ],
            [
                'key' => 'government',
                'name' => 'Government Offices',
                'description' => 'Maintain municipal offices, contacts, and services.',
                'path' => '/superadmin/government-offices-list.php',
                'icon' => 'fa-landmark-flag',
                'tags' => ['government', 'civic', 'directories'],
            ],
            [
                'key' => 'atms',
                'name' => 'ATM Network',
                'description' => 'Track ATMs and banking touchpoints across OMR.',
                'path' => '/superadmin/atms-list.php',
                'icon' => 'fa-building-columns',
                'tags' => ['atm', 'finance', 'directories'],
                'actions' => [
                    ['label' => 'Manage ATMs', 'path' => '/superadmin/manage-atms.php'],
                ],
            ],
        ],
    ],
    [
        'key' => 'technology',
        'label' => 'Technology & IT',
        'icon' => 'fa-microchip',
        'modules' => [
            [
                'key' => 'it_submissions',
                'name' => 'IT Submissions',
                'description' => 'Review IT company submissions and inbound leads.',
                'path' => '/superadmin/it-submissions-list.php',
                'icon' => 'fa-clipboard-list',
                'tags' => ['it', 'submissions', 'technology'],
            ],
            [
                'key' => 'it_companies',
                'name' => 'IT Companies',
                'description' => 'Manage IT company profiles and categories.',
                'path' => '/superadmin/it-companies-list.php',
                'icon' => 'fa-building',
                'tags' => ['it', 'companies', 'technology'],
            ],
            [
                'key' => 'featured_it',
                'name' => 'Featured IT Listings',
                'description' => 'Highlight premium IT companies and sponsorships.',
                'path' => '/superadmin/featured-it-list.php',
                'icon' => 'fa-star',
                'tags' => ['featured', 'it', 'technology'],
            ],
            [
                'key' => 'it_parks',
                'name' => 'IT Parks Hub',
                'description' => 'Maintain IT park details, tenants, and facilities.',
                'path' => '/superadmin/it-parks/manage.php',
                'icon' => 'fa-network-wired',
                'tags' => ['it', 'parks', 'technology'],
                'actions' => [
                    ['label' => 'Featured IT Parks', 'path' => '/superadmin/it-parks/featured.php'],
                    ['label' => 'Import & Export', 'path' => '/superadmin/it-parks/import-export.php'],
                ],
            ],
        ],
    ],
    [
        'key' => 'operations',
        'label' => 'Operations & Utilities',
        'icon' => 'fa-screwdriver-wrench',
        'modules' => [
            [
                'key' => 'migrations',
                'name' => 'Migrations Runner',
                'description' => 'Execute database migrations and schema updates (dev-tools).',
                'path' => '/superadmin/migrations-runner.php',
                'icon' => 'fa-database',
                'tags' => ['operations', 'database', 'maintenance'],
            ],
            [
                'key' => 'newsletter',
                'name' => 'Newsletter Subscribers',
                'description' => 'Export and review omr_newsletter_subscribers sign-ups.',
                'path' => '/superadmin/newsletter-subscribers.php',
                'icon' => 'fa-envelope',
                'tags' => ['newsletter', 'email', 'operations'],
            ],
            [
                'key' => 'change_password',
                'name' => 'Admin Security',
                'description' => 'Credentials are set in superadmin/_auth.php.',
                'path' => '/superadmin/change-password.php',
                'icon' => 'fa-user-shield',
                'tags' => ['security', 'account', 'operations'],
            ],
        ],
    ],
];


